print("YO: Que tal primo buenos dias")
print("PRIMO: todo bien ")
print("YO: Como va el clima en Santa Cruz?")
print("PRIMO: Aun esta haciendo calor y como esta por La Paz?")
print("YO: empeso el frio por aqui")
print("PRIMO: me lo imagino tendras que sacar tu ropa de abrigo")
print("YO: si eso voy hacer por el clima frio")
print("PRIMO: me tengo que ir al trabajo hablamos mas tarde bye!")
print("YO: ok hablamos mas tarde")